# Generated by Django 5.0.2 on 2025-06-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_id',
            field=models.CharField(default='', max_length=230, unique=True),
        ),
    ]
